name: "Playwright tests"

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Install Nix
      uses: cachix/install-nix-action@v27
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}

    - name: Start dev vm for database
      run: nix run .#dev-vm

    - name: Run playwright tests
      run: |
        cd web-app
        nix develop .#web
        npm install
        npm run test
